initializeParas;

% different parameters to look at
checkParas = {'choice' 'pursuit.APvelocityX' ...
    'pursuit.initialMeanVelocityX' 'pursuit.initialPeakVelocityX' ...
    'pursuit.gainX' ...
    'saccades.X.number' 'saccades.X.meanAmplitude' 'saccades.X.sumAmplitude'}; % field name in eyeTrialData
pdfNames = {'perception' 'APvelX' ...
    'olpMeanVelX' 'olpPeakVelX' ...
    'clpGainX' ...
    'sacNumX' 'sacMeanAmpX' 'sacSumAmpX'}; % name for saving the pdf
sacStart = 6; % from the n_th parameter is saccade

allLength = 682; % length of all trials in one block
sLength = 500; % length of standard trials in one block
pLength = 182; % length of perceptual trials in one block
trialBin = 2; % window of trial numbers

% some settings
individualPlots = 0;
averagedPlots = 1;
yLabels = {'Probability of perceiving right-probability of right' 'AP horizontal velocity (deg/s)' ...
    'olp mean horizontal velocity (deg/s)' 'olp peak horizontal velocity (deg/s)' ...
    'clp gain (horizontal)' ...
    'saccade number (horizontal)' 'saccade mean amplitude (horizontal)' 'saccade sum amplitude (horizontal)'};
% for plotting, each parameter has a specific y value range
minY = [0; -3; ...
    -10; -15; ...
    0; ...
    0; 0; 0];
maxY = [1; 3; ...
    10; 15; ...
    1.5; ...
    5; 2; 5];